version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  express:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    command: node server.js
    ports:
      - "8080:8080"

volumes:
  postgres: